In [2]:
import pandas as pd
import numpy as np


In [11]:
#1
print(np.zeros(10,dtype=int))
print(np.ones(10,dtype=int))
print(np.full(10,5))


[0 0 0 0 0 0 0 0 0 0]
[1 1 1 1 1 1 1 1 1 1]
[5 5 5 5 5 5 5 5 5 5]


In [17]:
#Create an array of the integers from 10 to 50.
np.arange(10,51)




array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [19]:
#5. Create an array of all the even integers from 10 to 50.
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [21]:

#7. Create a 3x3 identity matrix.
np.eye(3,3,dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [23]:
#6. Create a 3x3 matrix with values ranging from 0 to 8.
np.arange(0,9).reshape(3,3)


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [35]:
#8. Use NumPy to generate a random number between 0 and 1.
np.random.rand(10)


array([0.82089014, 0.48932899, 0.85165271, 0.82563012, 0.54158252,
       0.18878321, 0.80681622, 0.70809877, 0.33573996, 0.95708682])

In [37]:
#9. Use NumPy to generate an array of 25 random numbers sampled from a standard normal
#distribution.
np.random.randn(25)


array([ 1.02348738, -0.37016796,  1.29188303,  0.38902235,  0.026493  ,
        0.49050395, -0.73889297, -1.86483256, -1.00116309, -0.00957357,
       -1.09607942,  1.30775953,  0.70854672,  1.2807116 , -0.09435416,
       -0.13231436,  1.6901185 , -0.21407678, -0.95936003, -0.74800191,
       -1.16472656, -1.43206165, -0.42648066,  1.63451475,  0.66264265])

In [38]:
#10. Create an array of 20 linearly spaced points between 0 and 1.
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [78]:
#11. Create a 5x5 matrix with values from 1 to 25.
arr = np.random.randint(1,25,size=(5,5))
arr

array([[ 5, 22,  2, 15, 10],
       [20, 10, 22,  1,  3],
       [17,  2,  4, 12,  6],
       [20, 11,  8, 10, 24],
       [ 8, 23, 11,  4, 16]])

In [47]:
#12. Extract the first row of a 2D array.
arr[0]
#arr[3:,3:]

array([1, 2, 3, 4, 5])

In [49]:
#13. Extract the last column of a 2D array.
arr[:,4]

array([ 5, 10, 15, 20, 25])

In [50]:
#14. Find the sum of all elements in an array.
arr.sum()

325

In [51]:
#15. Find the standard deviation of an array.
arr.std()

7.211102550927978

In [71]:
#16. Find the index of the maximum value in an array.
#np.argmax(arr) -> converts the array in flatten array and return max element index
#np.unravel_index -> convert one d array to 2 d array row = 1 // shape and column = 1 % shape and return tuple (0,1)
np.unravel_index(np.argmax(arr),arr.shape)



(0, 1)

In [87]:
#17. Sort an array in ascending order.
np.sort(arr,0)


array([[ 1,  3,  6, 12, 17],
       [ 2,  4, 10, 15, 22],
       [ 2,  5, 10, 16, 22],
       [ 4,  8, 11, 20, 23],
       [ 8, 10, 11, 20, 24]])

In [93]:
#18. Reverse an array.
arr[::-1]

array([[ 2,  5, 10, 15, 22],
       [ 1,  3, 10, 20, 22],
       [ 2,  4,  6, 12, 17],
       [ 8, 10, 11, 20, 24],
       [ 4,  8, 11, 16, 23]])

In [94]:
#19. Create a diagonal matrix from a given array.
np.diag(arr)

array([ 2,  3,  6, 20, 23])

In [95]:
#20. Create a 4x4 matrix with random integers between 1 and 100.
np.random.randint(1,101,(4,4))

array([[56, 47, 52, 43],
       [89, 47, 40, 51],
       [ 1, 15, 18, 30],
       [27, 34, 16, 53]])